#!/bin/bash
set -euo pipefail

hostname=""
processor_model=""
lvm_partition=""
volume_group=""
default_kernel=""
physical_volume=""
root_secret=""
is_vm=""

set_time() {
    echo "Setting timezone and syncing hardware clock to system clock."
    ln -sf /usr/share/zoneinfo/America/Detroit /etc/localtime
    hwclock --systohc
    timedatectl set-ntp true
}

configure_locale() {
    echo "Generating and configuring locales"

    # Uncomment locale for en_US.UTF-8
    sed -i 's/^#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
    locale-gen

    # Set the console keyboard layout and font
    #loadkeys en
    #setconsolefont XXXX

    # Create locale configuration
    locale >> /etc/locale.conf

    # Set language variable
    sed -i '/^LANG=/c\LANG=en_US.UTF-8' /etc/locale.conf
}

set_hostname() {
    echo "Setting the hostname to $hostname..."
    echo "$hostname" > /etc/hostname
    echo ""

    # Update the /etc/hosts file
    echo "Updating /etc/hosts..."
    cat <<EOF > /etc/hosts
127.0.0.1   localhost
::1         localhost
127.0.1.1   $hostname.localdomain $hostname
EOF

    hostnamectl set-hostname "$hostname"
    echo "Hostname and /etc/hosts updated successfully!"
}

install_ucode() {
    echo "Detecting processor type for microcode installation..."

    # Determine the appropriate microcode package
    local ucode_package
    if echo "$processor_model" | grep -iq "Intel"; then
        ucode_package="intel-ucode"
        echo "Intel processor detected."
    elif echo "$processor_model" | grep -iq "AMD"; then
        ucode_package="amd-ucode"
        echo "AMD processor detected."
    else
        echo "Unknown processor type. Skipping microcode installation."
        echo ""
        return 
    fi

    # Check if the microcode package is already installed
    if pacman -Qq "$ucode_package" > /dev/null 2>&1; then
        echo "$ucode_package is already installed. Skipping."
        echo ""
        return 
    fi

    # Install the appropriate microcode package
    echo "Installing $ucode_package..."
    pacman -S --noconfirm "$ucode_package"
    echo ""
}



main() {
    set_time
    configure_locale
    set_hostname
    install_ucode
}

main
